datamodule:
  _target_: fdiff.dataloaders.datamodules.GluonTSJsonDatamodule
  data_dir: ${oc.env:FDIFF_DATA_DIR,""}   # 没设环境变量就给空串，后续 prepare_data 会报更友好的错误
  batch_size: 64
  window_length: 360
  pred_len: 30
  stride: 1
  standardize: true
  num_workers: 4
  pin_memory: true
  val_ratio: 0.1
  jsonl_train:
  jsonl_test:
