# 与仓库其它数据集配置风格一致：datamodule 是类路径字符串，超参全在根层
datamodule: fdiff.dataloaders.datamodules.GluonTSJsonDatamodule

data_dir: ${oc.env:FDIFF_DATA_DIR,""}
batch_size: 64
window_length: 60
pred_len: 30
stride: 1
standardize: true
num_workers: 4
pin_memory: true
val_ratio: 0.1

jsonl_train:
jsonl_test:
